version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'rmq-user'
      RABBITMQ_DEFAULT_PASS: 'rmq-pass'