version: '3.7'

services:
  database:
    container_name: user-db
    image: postgres:alpine
    ports:
      - '5400:5433'
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres