server:
  port: 8191
spring:
  flyway:
    locations: classpath:migrations
    url: jdbc:postgresql://localhost:5433/users-db
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/users-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
        ddl-auto: validate
