version: '3.7'

services:
  minio:
    image: bitnami/minio:2023.4.28
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminqwerty
    volumes:
      - minio-data:/data
    ports:
      - 9900:9000
      - 9901:9001
  database:
    container_name: file-storage-db
    image: postgres:alpine
    ports:
      - '5404:5433'
    environment:
      - POSTGRES_DB=file-storage-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  minio-data:


